services:
  - type: web
    name: hummify
    env: docker
    plan: free
    autoDeploy: true
    envVars:
      - key: MONGO_URI
      - key: CLOUDINARY_URL
      - key: CLOUDINARY_CLOUD_NAME
      - key: CLOUDINARY_API_KEY
      - key: CLOUDINARY_API_SECRET
      - key: JWT_SECRET
      - key: JWT_EXPIRE
      - key: CLIENT_URL
      - key: PORT
