
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - CHOKIDAR_USEPOLLING=true  
      - CHOKIDAR_INTERVAL=1000
      - NODE_ENV=development
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app          
      - /app/node_modules 
    restart: unless-stopped
   
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_WATCH=true 
      - VITE_BACKEND_URL=http://backend:5000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend
