version: '3'
services:
  backend:
    build: ./backend
    ports:
      - "5000:5000"
    environment:
      - CLIENT_URL
      - MONGO_URI
      - CLOUDINARY_URL
      - CLOUDINARY_CLOUD_NAME
      - CLOUDINARY_API_SECRET
      - CLOUDINARY_API_KEY
      - PORT
      - CHOKIDAR_USEPOLLING=true  
      - CHOKIDAR_INTERVAL=1000
      - NODE_ENV=development
    env_file:
      - .env
    volumes:
      - ./backend:/app          
      - /app/node_modules 
    restart: unless-stopped
   
  frontend:
    build: ./frontend
    ports:
      - "5173:5173"
    environment:
      - VITE_WATCH=true 
    volumes:
      - ./frontend:/app
      - /app/node_modules
    restart: unless-stopped
    depends_on:
      - backend
