services:
  - type: web
    name: hummify-backend
    env: docker
    repo: https://github.com/archis04/hummify
    region: oregon
    dockerfilePath: ./backend/Dockerfile
    buildFilter:
      paths:
        - backend/**
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 5000
      - key: MONGO_URI
        value: mongodb+srv://archis:M%3Dt%40l_..100.@cluster0.ma33fpr.mongodb.net/arc?retryWrites=true&w=majority&appName=Cluster0
      - key: CLOUDINARY_URL
        value: cloudinary://285781232978814:YUfmHhi8EMhWSVUGFa9YkDizE5Q@dh6dt6w6z
      - key: CLOUDINARY_CLOUD_NAME
        value: dh6dt6w6z
      - key: CLOUDINARY_API_KEY
        value: 285781232978814
      - key: CLOUDINARY_API_SECRET
        value: YUfmHhi8EMhWSVUGFa9YkDizE5Q
      - key: JWT_SECRET
        value: e1108a17000d80554364446f33b3b4f16a3ef9c5cb60885b94c9eea17f8e7272
      - key: JWT_EXPIRE
        value: 7d
      - key: CLIENT_URL
        value: https://hummify-frontend.onrender.com
      - key: TF_CPP_MIN_LOG_LEVEL
        value: "3"

  - type: web
    name: hummify-frontend
    env: docker
    repo: https://github.com/archis04/hummify
    region: oregon
    dockerfilePath: ./frontend/Dockerfile
    buildFilter:
      paths:
        - frontend/**
    envVars:
      - key: VITE_BACKEND_URL
        value: https://hummify-backend.onrender.com
